app/blogs/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Length, Email,EqualTo


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField( 'Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')


class LoginForm(FlaskForm):
    email = StringField( 'Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

class PostForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired()])
    body = TextAreaField('Text',validators=[DataRequired()])
    submit = SubmitField("Submit")


class CommentForm(FlaskForm):
    body = TextAreaField('Text',validators=[DataRequired()])
    submit = SubmitField("Submit")

app/blogs/__init__.py
from flask import Blueprint
blogs = Blueprint('blogs',__name__)
from . import views

app/blogs/views.py
from flask import render_template, url_for, request, redirect, flash
from flask_login import current_user, login_required
from app import db
from app.models import Blog, User, Comment
from app.blogs.forms import PostForm, CommentForm
from app.blogs import blogs



# CREATE A BLOG

@blogs.route('/create', methods = ['GET', 'POST'])
@login_required
def create_post():
    post_form = PostForm()
    if post_form.validate_on_submit():
        post = Blog(title = post_form.title.data,
                    body = post_form.body.data,
                    user_id = current_user.id)
        db.session.add(post)
        db.session.commit()
        flash('Post saved')
        return redirect(url_for('main.index'))
    return render_template('blog/create_post.html', post_form=post_form)


# VIEW A POST
@blogs.route('blog/<int:post_id>')
def post(post_id):
    post = Blog.query.get_or_404(post_id)
    return render_template('blog/post.html', title =post.title, date = post.timestamp, post = post)



@blogs.route('blog/<int:post_id>/update', methods = ['GET', 'POST'])
@login_required
def update(post_id):
    '''
    function to update post
    '''
    post = Blog.query.get_or_404(post_id)
    if post.author!=current_user:
        #403 error is forbidden
        abort(403)
    post_form  = PostForm()

    if post_form.validate_on_submit():
        post.title = post_form.title.data
        post.body = post_form.body.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('blogs.post', post_id=post.id))

    elif request.method == 'GET':
        post_form.title.data = post.title
        post_form.body.data = post.body

    return render_template('blog/create_post.html',title = 'Updating', post_form = post_form)


@blogs.route('blog/<int:post_id>/delete', methods = ['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Blog.query.get_or_404(post_id)
    if post.author!=current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()

    flash('Post deleted.')
    return redirect(url_for('main.index'))



@blogs.route('/comment/<post_id>', methods = ['GET','POST'])
@login_required
def comment(post_id):
    post = Blog.query.get_or_404(post_id)
    form_comment = CommentForm()

    if form_comment.validate_on_submit():
        comment = Comment(body = form_comment.body.data,
                            blog_id = post.id,
                          author_id= current_user.id)
        db.session.add(comment)
        db.session.commit()
        flash('Comments added successfuly!')
        return redirect(url_for('blogs.post',post_id =post_id))

    from pprint import pprint
    print(post)
    return render_template('blog/comments.html',post =post, form_comment=form_comment)
    

app/templates/blog/comments.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container"> 
        <div class="row">
          <div class= "col-md-2"> </div>
          <div class="col-md-8">
          <!-- Create Post form -->
          {{wtf.quick_form(form_comment)}}
         </div>
         <div clas="col-md-2"> </div>
        </div>
    </div>
    

{% endblock %}

app/templates/blog/create_post.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container"> 
        <div class="row">
          <div class= "col-md-2"> </div>
          <div class="col-md-8">
          <!-- Create Post form -->
          {{wtf.quick_form(post_form)}}
         </div>
         <div clas="col-md-2"> </div>
        </div>
    </div>
    

{% endblock %}

app/templates/blog/post.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}



{% block content %}
<div class="container">
    <h2>{{title}}</h2>
    
    <h4>Date published: {{post.timestamp.strftime('%B %d, %Y')}}</h4>
    <p>
        {{post.body}}

    </p>
    <div>
      <!-- <a href="{{ url_for('.post', post_id=post.id) }}">Comment -->
          <a href="{{ url_for('blogs.comment', post_id=post.id) }}">Comment
      
          

          <span class="label label-primary">
              {{ post.comments.count() }} Comments
          </span>
      
      </a>

    </div>

    {% if post.author == current_user %}
    <div>

        <a href="{{url_for('blogs.update', post_id = post.id)}}">Update</a>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete_post">Delete</button>
    </div>

    {% endif %}

</div>
<div class="modal" tabindex="-1" role="dialog" id="delete_post">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Delete Post?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Confirm if you want to the delete post!</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <form action="{{url_for('blogs.delete_post', post_id = post.id)}}" method="POST">
                  <input class="btn btn-danger" type="submit" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>



{% endblock  %}